### ISSUE TITLE
Packagist didn't catch newest version - 1.0.1.2

### ISSUE THREAD

**Issue by evilprophet** [wallee-payment/magento-2.2#1]
**Actual result**
I can install only 1.0.1 or 1.0.0
**Expected**
I want to install 1.0.1.2

Your newest version 1.0.1.2 isn't caught by packagist because in composer.json you still have 1.0.1.

https://packagist.org/packages/wallee/magento-2
https://github.com/wallee-payment/magento-2/blob/master/composer.json

**Comment by schurter-wallee** [comment]
We just released version 1.0.3 of the extension. This should solve the problem.
