### ISSUE TITLE
Fooman Surcharge serialization error

### ISSUE THREAD

**Issue by jmenz** [wallee-payment/magento-2.2#13]
When fooman surcharge is used in a quote, `\Wallee\Sdk\ObjectSerializer::sanitizeForSerialization`
throws the exception:
`Uncaught Error: Call to undefined method Magento\Framework\Phrase::swaggerTypes() in /var/www/site/vendor/wallee/sdk/lib/ObjectSerializer.php:152`

This happens because of the \Magento\Framework\Phrase object is passed as a $label parameter into `\Wallee\Payment\Observer\CollectFoomanSurchargeLineItems::createSurchargeLineItem` method.

As it's not converted to a string, there is a serializer exception.

Suggest to convert it to a string before set to $surcharge object.
`$surcharge->setName((string)$label);`
Here is a changed method:

```
private function createSurchargeLineItem($entity, $currency, $amount, $taxAmount, $code, $label)
    {
        $surcharge = new LineItemCreate();
        $surcharge->setType(LineItemType::FEE);
        $surcharge->setAmountIncludingTax($this->helper->roundAmount($amount + $taxAmount, $currency));
        $surcharge->setSku('fooman-surcharge');
        $surcharge->setUniqueId('fooman_surcharge_' . $code);
        $surcharge->setName((string)$label);//this is the only change
        $surcharge->setQuantity(1);
        $surcharge->setShippingRequired(false);
        if ($taxAmount > 0) {
            $tax = $this->getTax($entity, $code);
            if ($tax instanceof TaxCreate) {
                $surcharge->setTaxes([
                    $tax
                ]);
            }
        }
        return $surcharge;
    }
```

**Comment by schurter-wallee** [comment]
Fixed in version 1.0.59.
