### ISSUE TITLE
can't create order on backoffice and pay with wallee

### ISSUE THREAD

**Issue by mvistas** [wallee-payment/magento-2.2#14]
Hello

I want to create orders through backoffice and pay with wallee invoice.
I activate the tokenization on wallee backofice.
When a choose the wallee invoice payment I can't see any token drodown and if I try to create my order on backoffice I get message: 
_**"Order saving error: The wallee payment transaction is not set on the quote."**_

how can I fix this?

Thank you and Best regards

**Comment by theodorspringwallee** [comment]
already answered through support request:
> It is not possible to use invoice for ONFILE payments as no ONFILE / sensitive ONFILE Data is needed for this. You can simply re-execute the transaction with invoice. In order to provide Invoice as a recurring payment method it depends on how the merchant sets the subscription process up. If they use our subscription API they can define allowed payment methods / invoice for any subscription product. Once the transaction is created a charge flow is executed - if invoice is eligible, and no token is present the payment method is used.

For other solutions the merchant only has to trigger a charge flow in order to trigger the process mentioned above.
